

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: yourRootPass
      MYSQL_DATABASE: hoteldb
      MYSQL_USER: hoteluser
      MYSQL_PASSWORD: hotelpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis-local
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: